# site settings
title: Siqi's Space
subtitle: 
email: sx86@cornell.edu
description: Master of Engineering Student at Cornell University Major in Operation Research and Information Engineering
baseurl: ''
url: https://siqiiii.github.io
author: Siqi Xie
street_address: 112 Valentine Pl
city: Ithaca
state: NY
zip_code: 14850
country: United States of America
phone: (919) 448-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/siqiiii
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/siqi-xie
  Twitter: 
  Facebook: https://www.facebook.com/sara.xie/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
